inputs = ["**/*2.13*/**/jacoco.xml"]
exclude_paths = []
verbose = true

rules = [
    # filter-out method from AtumAgent class
    #"method:za.co.absa.atum.agent.AtumAgent#dispatcherFromConfig*",

    # filter-out method from AtumAgent object
    #"method:za.co.absa.atum.agent.AtumAgent$#dispatcherFromConfig*"
]
