inputs = ["**/*2.13*/**/jacoco.xml"]
exclude_paths = []
verbose = true

rules = [
    "method:za.co.absa.atum.agent.AtumAgent#dispatcherFromConfig*",
    "method:za.co.absa.atum.agent.AtumAgent$#dispatcherFromConfig*"
]
