# Copyright 2021 ABSA Group Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'atum_server_http4s'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          env: 'local'
          app: 'atum'
  - job_name: 'atum_server_zio_runtime'
    metrics_path: /zio-metrics
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          env: 'local'
          app: 'atum'
