name: Auto Assign Issue to Project

on:
  issues:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign issue to Project
    steps:
    - name: Assign NEW issues to a project
      uses: srggrs/assign-one-project-github-action@1.3.1
      with:
        project: 'https://github.com/orgs/AbsaOSS/projects/7'
        column_name: 'New'
